package com.example.mshcincapacidades.Model.Notas;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.Data;

@Document(value="mc_salud_hos_nt_med_ginecologia_stg")
@Data
public class NotaInicialGinecologiaDetail{
    @Id
    public String _id;
    public String des_nombre_completo;
    public String num_edad;
    public String ind_sexo;
    public String cve_pac_nss;
    public String cve_pac_amedico;
    public String cve_pac_curp;
    public String cve_ooad;
    public String des_ooad;
    public String des_unidad;
    public String cve_especialidad;
    public String cve_servicio;
    public String cve_nivel;
    public String des_diagnostico;
    public String des_notas;
    public String fec_nota;
    public String num_exp_folio;
    public String num_exp_anio;
    public String num_exp_unidado;
    public String cve_exp_cvesol;
    public String num_exp_consec;
    public String cve_exp_nss;
    public String cve_exp_medicof;
    public String cve_hos_nss;
    public String cve_hos_amedico;
    public String cve_hos_calidad;
    public String num_estatura;
    public String num_peso;
    public String num_temperatura;
    public String num_tension_arterial;
    public String num_frecuencia_cardiaca;
    public String num_frecuencia_repiratoria;
    public String num_glucosa;
    public String num_saturacion_oxigeno;
    public String des_resumen_interrog_planestd;
    public String des_pronostico;
    public String des_complicacion;
    public String num_folio_ginecologia;
    public String num_gesta;
    public String num_menarca;
    public String ind_para;
    public String des_grupo_sanguineo;
    public String num_abortos;
    public String num_cesareas;
    public String num_amenorrea;
    public String fec_fum;
    public String ind_edema;
    public String ind_dolor_obstetrico;
    public String ind_hiperflexia;
    public String ind_acufenos;
    public String ind_alteracion_pulmonares;
    public String ind_fosfenos;
    public String ind_especificacion_alteraciones;
    public String ind_epigastralgia;
    public String ind_especificacion_dolor;
    public String ind_activar_alerta_maternal;
    public String ind_embarazo_ectopico;
    public String num_fondo_uterino;
    public String num_contracciones;
    public String ind_tono_uterino;
    public String ind_frecuencia_cardiaca_fetal;
    public String ind_dilatacion;
    public String ind_consistencia;
    public String ind_dorso;
    public String ind_hemorragia;
    public String ind_actividad_uterina;
    public String fec_mem_rotas;
    public String num_longitud;
    public String ind_situacion;
    public String ind_pss;
    public String hora_mem_rotas;
    public String ind_altura_hodge;
    public String ind_presentacion;
    public String ind_cristalografia;
    public String ind_aspecto_liquido;
    public String des_pronostico_ginecologia;
    public String ind_consiente;
    public String ind_paciente_obstetricia;
    public String fec_cardiopatia;
    public String fec_hepatopatia;
    public String fec_cirugia_pelvica;
    public String fec_hipertension_arterial;
    public String fec_diabetes_mellitus;
    public String fec_nefropatia;
    public String fec_enfermedades_inmunologicas;
    public String fec_tuberculosis;
    public String fec_eclampsia;
    public String fec_obito;
    public String fec_rnmay25000;
    public String fec_embarazo_ectopico;
    public String fec_partoprematuro;
    public String fec_preclamsia;
    public String fec_cesarea;
    public String fec_perdidag_estacion;
    public String fec_infertilidad;
    public String fec_rnmay4000;
    public String des_transfusiones;
    public String des_alergico;
    public String des_tabaquismo;
    public String des_etilismo;
    public String des_toxicomanias;
    public String cve_med_matricula;
    public String des_nombre_medico;
    public String cve_med_cedula;
    public String num_borramiento;
    public String ind_posicion;
    public String ind_cefalea;
    public String des_ultrasonido;
    public String des_laboratorio;
    public String ind_membranas;
    public String des_tipo_hemorragia;
    public String des_diagnostico_mtratante;
    public String cve_estatus_expediente;
    public String fecha_proceso;
    public String num_anio_partition;
  
}
